---

#Installation des paquets mariadb serveur et son extension Pythonù
- name: "mariadb-server installation"
  apt:
    name: "mariadb-server,python,python3-mysqldb"
    state: "present"

#Active le service MariaDB
- name: "start mariadb service"
  service : 
    name: "mariadb"
    state: "started"
    enabled: "yes"

# Active l ecoute sur tous les ports IPv4
- name: "change 50-serve.cnf"
  command:
    /bin/sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mysql/mariadb.conf.d/50-server.cnf

# Restart mariadb
- name: "restart mariadb"
  service:
    name: "mariadb"
    state: restarted
